services:
  regex-web:
    build: .
    networks:
      - dokploy-network
  regex-www:
    image: beeman/static-server:latest
    environment:
      - REDIRECT_URL=https://regex.colmena.dev
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
